-- https://v3rmillion.net/showthread.php?tid=1023761

loadstring(game:HttpGet("https://pastebin.com/raw/C2vZT38V"))()
local UILibrary = loadstring(game:HttpGet("https://pastebin.com/raw/V1ca2q9s"))()
local MainUI = UILibrary.Load("Comatose - Edward's bs train")
local Guns = MainUI.AddPage("Guns")
local Titles = MainUI.AddPage("Titles")
local Mix = MainUI.AddPage("Mix")


local FirstLabel = Guns.AddLabel(DiscordTag)
local FirstLabel = Titles.AddLabel(DiscordTag)
local FirstLabel = Mix.AddLabel(DiscordTag)



local FirstButton = Guns.AddButton("Inf Ammo (HoldOutGun)", function()
    while wait() do 
        for i,v in pairs(game.Players.LocalPlayer.Character:GetDescendants()) do
          if v:IsA("Tool") then
            v["IntValue_CurrentReserve"].Value = 100
            v["IntValue_CurrentMagazine"].Value = 100
        end  
        end
        end
end)


local FirstButton = Guns.AddButton("DeBugger Gun", function()
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_RequestWeaponPurchase:InvokeServer(unpack({[1] = "Weapon_TheDebugger",[2] = 0}))
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_SelectPlayerWeapon:InvokeServer(unpack({[1] = "Weapon_TheDebugger",[2] = 1}))
end)

local FirstButton = Guns.AddButton("UnLock all guns", function()
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_RequestWeaponPurchase:InvokeServer(unpack({[1] = "Weapon_TheDebugger",[2] = 0}))
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_SelectPlayerWeapon:InvokeServer(unpack({[1] = "Weapon_TheDebugger",[2] = 1}))
    wait()
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_RequestWeaponPurchase:InvokeServer(unpack({[1] = "Weapon_AU47",[2] = 0}))
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_SelectPlayerWeapon:InvokeServer(unpack({[1] = "Weapon_AU47",[2] = 1}))
    wait()
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_RequestWeaponPurchase:InvokeServer(unpack({[1] = "Weapon_BaxterSpecial",[2] = 0}))
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_SelectPlayerWeapon:InvokeServer(unpack({[1] = "Weapon_BaxterSpecial",[2] = 1}))
    wait()
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_RequestWeaponPurchase:InvokeServer(unpack({[1] = "Weapon_Bergmann510Sport",[2] = 0}))
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_SelectPlayerWeapon:InvokeServer(unpack({[1] = "Weapon_Bergmann510Sport",[2] = 1}))
    wait()
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_RequestWeaponPurchase:InvokeServer(unpack({[1] = "Weapon_Bergmann500",[2] = 0}))
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_SelectPlayerWeapon:InvokeServer(unpack({[1] = "Weapon_Bergmann500",[2] = 1}))
    wait()
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_RequestWeaponPurchase:InvokeServer(unpack({[1] = "Weapon_CobraMagnum",[2] = 0}))
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_SelectPlayerWeapon:InvokeServer(unpack({[1] = "Weapon_CobraMagnum",[2] = 1}))
    wait()
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_RequestWeaponPurchase:InvokeServer(unpack({[1] = "Weapon_Earnshaw700",[2] = 0}))
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_SelectPlayerWeapon:InvokeServer(unpack({[1] = "Weapon_Earnshaw700",[2] = 1}))
    wait()
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_RequestWeaponPurchase:InvokeServer(unpack({[1] = "Weapon_Earnshaw800M",[2] = 0}))
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_SelectPlayerWeapon:InvokeServer(unpack({[1] = "Weapon_Earnshaw800M",[2] = 1}))
    wait()
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_RequestWeaponPurchase:InvokeServer(unpack({[1] = "Weapon_F17C",[2] = 0}))
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_SelectPlayerWeapon:InvokeServer(unpack({[1] = "Weapon_F17C",[2] = 1}))
    wait()
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_RequestWeaponPurchase:InvokeServer(unpack({[1] = "Weapon_GunslingerMagnum",[2] = 0}))
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_SelectPlayerWeapon:InvokeServer(unpack({[1] = "Weapon_GunslingerMagnum",[2] = 1}))
    wait()
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_RequestWeaponPurchase:InvokeServer(unpack({[1] = "Weapon_Hollingsworth1894",[2] = 0}))
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_SelectPlayerWeapon:InvokeServer(unpack({[1] = "Weapon_Hollingsworth1894",[2] = 1}))
    wait()
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_RequestWeaponPurchase:InvokeServer(unpack({[1] = "Weapon_1894Tactical",[2] = 0}))
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_SelectPlayerWeapon:InvokeServer(unpack({[1] = "Weapon_1894Tactical",[2] = 1}))
    wait()
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_RequestWeaponPurchase:InvokeServer(unpack({[1] = "Weapon_CustomHollingsworth1894",[2] = 0}))
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_SelectPlayerWeapon:InvokeServer(unpack({[1] = "Weapon_CustomHollingsworth1894",[2] = 1}))
    wait()
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_RequestWeaponPurchase:InvokeServer(unpack({[1] = "Weapon_MA16",[2] = 0}))
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_SelectPlayerWeapon:InvokeServer(unpack({[1] = "Weapon_MA16",[2] = 1}))
    wait()
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_RequestWeaponPurchase:InvokeServer(unpack({[1] = "Weapon_MA16Marksman",[2] = 0}))
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_SelectPlayerWeapon:InvokeServer(unpack({[1] = "Weapon_MA16Marksman",[2] = 1}))
    wait()
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_RequestWeaponPurchase:InvokeServer(unpack({[1] = "Weapon_MUAS12",[2] = 0}))
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_SelectPlayerWeapon:InvokeServer(unpack({[1] = "Weapon_MUAS12",[2] = 1}))
    wait()
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_RequestWeaponPurchase:InvokeServer(unpack({[1] = "Weapon_Moretti90R",[2] = 0}))
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_SelectPlayerWeapon:InvokeServer(unpack({[1] = "Weapon_Moretti90R",[2] = 1}))
    wait()
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_RequestWeaponPurchase:InvokeServer(unpack({[1] = "Weapon_PUAS12",[2] = 0}))
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_SelectPlayerWeapon:InvokeServer(unpack({[1] = "Weapon_PUAS12",[2] = 1}))
    wait()
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_RequestWeaponPurchase:InvokeServer(unpack({[1] = "Weapon_RAC10",[2] = 0}))
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_SelectPlayerWeapon:InvokeServer(unpack({[1] = "Weapon_RAC10",[2] = 1}))
    wait()
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_RequestWeaponPurchase:InvokeServer(unpack({[1] = "Weapon_RAC10Commando",[2] = 0}))
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_SelectPlayerWeapon:InvokeServer(unpack({[1] = "Weapon_RAC10Commando",[2] = 1}))
    wait()
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_RequestWeaponPurchase:InvokeServer(unpack({[1] = "Weapon_SP1911",[2] = 0}))
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_SelectPlayerWeapon:InvokeServer(unpack({[1] = "Weapon_SP1911",[2] = 1}))
    wait()
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_RequestWeaponPurchase:InvokeServer(unpack({[1] = "Weapon_AbbottSpecial",[2] = 0}))
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_SelectPlayerWeapon:InvokeServer(unpack({[1] = "Weapon_AbbottSpecial",[2] = 1}))
    wait()
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_RequestWeaponPurchase:InvokeServer(unpack({[1] = "Weapon_SP9Mini",[2] = 0}))
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_SelectPlayerWeapon:InvokeServer(unpack({[1] = "Weapon_SP9Mini",[2] = 1}))
    wait()
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_RequestWeaponPurchase:InvokeServer(unpack({[1] = "Weapon_SawedOffModel3",[2] = 0}))
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_SelectPlayerWeapon:InvokeServer(unpack({[1] = "Weapon_SawedOffModel3",[2] = 1}))
    wait()
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_RequestWeaponPurchase:InvokeServer(unpack({[1] = "Weapon_AU47M",[2] = 0}))
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_SelectPlayerWeapon:InvokeServer(unpack({[1] = "Weapon_AU47M",[2] = 1}))
    wait()
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_RequestWeaponPurchase:InvokeServer(unpack({[1] = "Weapon_Bergmann510Police",[2] = 0}))
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_SelectPlayerWeapon:InvokeServer(unpack({[1] = "Weapon_Bergmann510Police",[2] = 1}))
    wait()
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_RequestWeaponPurchase:InvokeServer(unpack({[1] = "Weapon_1894Tactical",[2] = 0}))
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_SelectPlayerWeapon:InvokeServer(unpack({[1] = "Weapon_1894Tactical",[2] = 1}))
    wait()
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_RequestWeaponPurchase:InvokeServer(unpack({[1] = "Weapon_CustomHollingsworth1894",[2] = 0}))
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_SelectPlayerWeapon:InvokeServer(unpack({[1] = "Weapon_CustomHollingsworth1894",[2] = 1}))
    wait()
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_RequestWeaponPurchase:InvokeServer(unpack({[1] = "Weapon_MA16",[2] = 0}))
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_SelectPlayerWeapon:InvokeServer(unpack({[1] = "Weapon_MA16",[2] = 1}))
    wait()
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_RequestWeaponPurchase:InvokeServer(unpack({[1] = "Weapon_MA16Marksman",[2] = 0}))
    game:GetService("ReplicatedStorage").Weapons_ReplicatedStorage.RemoteFunction_SelectPlayerWeapon:InvokeServer(unpack({[1] = "Weapon_MA16Marksman",[2] = 1}))
    wait()
end)

local FirstButton = Titles.AddButton("Developer Title", function()
    game:GetService("ReplicatedStorage").TitleManager_ReplicatedStorage.RemoteFunction_SelectPlayerTitle:InvokeServer(unpack({[1] = "Title_Developer"}))
end)

local FirstButton = Titles.AddButton("UnLock all Title", function()
    game:GetService("ReplicatedStorage").TitleManager_ReplicatedStorage.RemoteFunction_SelectPlayerTitle:InvokeServer(unpack({[1] = "Title_Attendant"}))
    wait()
    game:GetService("ReplicatedStorage").TitleManager_ReplicatedStorage.RemoteFunction_SelectPlayerTitle:InvokeServer(unpack({[1] = "Title_Fettler"}))
    wait()
    game:GetService("ReplicatedStorage").TitleManager_ReplicatedStorage.RemoteFunction_SelectPlayerTitle:InvokeServer(unpack({[1] = "Title_HiredGun"}))
    wait()
    game:GetService("ReplicatedStorage").TitleManager_ReplicatedStorage.RemoteFunction_SelectPlayerTitle:InvokeServer(unpack({[1] = "Title_Passenger"}))
    wait()
    game:GetService("ReplicatedStorage").TitleManager_ReplicatedStorage.RemoteFunction_SelectPlayerTitle:InvokeServer(unpack({[1] = "Title_Pilgrim"}))
    wait()
    game:GetService("ReplicatedStorage").TitleManager_ReplicatedStorage.RemoteFunction_SelectPlayerTitle:InvokeServer(unpack({[1] = "Title_Tourist"}))
    wait()
    game:GetService("ReplicatedStorage").TitleManager_ReplicatedStorage.RemoteFunction_SelectPlayerTitle:InvokeServer(unpack({[1] = "Title_Conductor"}))
    wait()
    game:GetService("ReplicatedStorage").TitleManager_ReplicatedStorage.RemoteFunction_SelectPlayerTitle:InvokeServer(unpack({[1] = "Title_Mercenary"}))
    wait()
    game:GetService("ReplicatedStorage").TitleManager_ReplicatedStorage.RemoteFunction_SelectPlayerTitle:InvokeServer(unpack({[1] = "Title_Drifter"}))
    wait()
    game:GetService("ReplicatedStorage").TitleManager_ReplicatedStorage.RemoteFunction_SelectPlayerTitle:InvokeServer(unpack({[1] = "Title_Stranger"}))
    wait()
    game:GetService("ReplicatedStorage").TitleManager_ReplicatedStorage.RemoteFunction_SelectPlayerTitle:InvokeServer(unpack({[1] = "Title_Citizen"}))
    wait()
    game:GetService("ReplicatedStorage").TitleManager_ReplicatedStorage.RemoteFunction_SelectPlayerTitle:InvokeServer(unpack({[1] = "Title_Dogcatcher"}))
    wait()
    game:GetService("ReplicatedStorage").TitleManager_ReplicatedStorage.RemoteFunction_SelectPlayerTitle:InvokeServer(unpack({[1] = "Title_Councilperson"}))
    wait()
    game:GetService("ReplicatedStorage").TitleManager_ReplicatedStorage.RemoteFunction_SelectPlayerTitle:InvokeServer(unpack({[1] = "Title_AbbottLoyalist"}))
    wait()
    game:GetService("ReplicatedStorage").TitleManager_ReplicatedStorage.RemoteFunction_SelectPlayerTitle:InvokeServer(unpack({[1] = "Title_BaxterLoyalist"}))
    wait()
    game:GetService("ReplicatedStorage").TitleManager_ReplicatedStorage.RemoteFunction_SelectPlayerTitle:InvokeServer(unpack({[1] = "Title_Floorhand"}))
    wait()
    game:GetService("ReplicatedStorage").TitleManager_ReplicatedStorage.RemoteFunction_SelectPlayerTitle:InvokeServer(unpack({[1] = "Title_Roughneck"}))
    wait()
    game:GetService("ReplicatedStorage").TitleManager_ReplicatedStorage.RemoteFunction_SelectPlayerTitle:InvokeServer(unpack({[1] = "Title_QATester"}))
    wait()
    game:GetService("ReplicatedStorage").TitleManager_ReplicatedStorage.RemoteFunction_SelectPlayerTitle:InvokeServer(unpack({[1] = "Title_Investor"}))
    wait()
    game:GetService("ReplicatedStorage").TitleManager_ReplicatedStorage.RemoteFunction_SelectPlayerTitle:InvokeServer(unpack({[1] = "Title_FirstClass"}))
    wait()
    game:GetService("ReplicatedStorage").TitleManager_ReplicatedStorage.RemoteFunction_SelectPlayerTitle:InvokeServer(unpack({[1] = "Title_Developer"}))
    wait()
end)


local FirstButton = Mix.AddButton("ProximintyPrompt Cooldown - 0", function()
    game:GetService("ProximityPromptService").PromptButtonHoldBegan:Connect(function(prompt)
        prompt.HoldDuration = 0
    end)    
end)


local FirstButton = Mix.AddButton("InfHeal", function()
    while wait() do
    game:GetService("ReplicatedStorage").Medical_ReplicatedStorage.RemoteEvent_RequestHealth:FireServer(unpack({[1] = 1000}))
    end
end)

local FirstLabel = Mix.AddLabel("Use the command :fling")
local FirstButton = Mix.AddButton("Infiniteyield", function()
    loadstring(game:HttpGet(('https://raw.githubusercontent.com/EdgeIY/infiniteyield/master/source'),true))()
end)







